# Import the 'os' module to interact with the operating system.
import os
# Import the 'load_dotenv' function from the 'dotenv' library. 
# This function is used to load environment variables from a '.env' file.
from dotenv import load_dotenv
# Import necessary classes from the 'agents' module.
# 'Agent' represents an autonomous agent.
# 'Runner' handles the execution of agents.
# 'set_default_openai_client' is a function to set the default OpenAI client.
# 'AsyncOpenAI' is an asynchronous client for interacting with OpenAI APIs.
# 'OpenAIChatCompletionsModel' represents a specific language model for chat completions.
# 'set_tracing_disabled' is a function to disable tracing of agent activities.
from agents import (
    Agent,
    Runner,
    set_default_openai_client,
    AsyncOpenAI,
    OpenAIChatCompletionsModel,
    set_tracing_disabled
)

# Load environment variables from a '.env' file if it exists in the current directory.
load_dotenv()

# Retrieve the value of the 'GEMINI_API_KEY' environment variable using 'os.getenv()'.
gemini_api_key = os.getenv("GEMINI_API_KEY")
# Check if the 'GEMINI_API_KEY' is not set (i.e., it's None or an empty string).
if not gemini_api_key:
    # If the API key is not set, raise a ValueError with a descriptive message,
    # indicating that the environment variable needs to be configured.
    raise ValueError("GEMINI_API_KEY is not set in the environment variables.")

# Create an instance of the 'AsyncOpenAI' client.
# This client is configured to interact with the Gemini API.
# 'api_key' is set to the retrieved 'gemini_api_key' for authentication.
# 'base_url' is set to the specific endpoint for the Gemini API that mimics the OpenAI API structure.
external_client = AsyncOpenAI(
    api_key = gemini_api_key,
    base_url = "https://generativelanguage.googleapis.com/v1beta/openai/"
)

# Set the newly created 'external_client' as the default OpenAI client to be used by the 'agents' library.
set_default_openai_client(external_client)
# Disable tracing within the 'agents' library. Tracing is used for debugging and monitoring agent behavior.
set_tracing_disabled(True)

# Create an instance of the 'OpenAIChatCompletionsModel'.
# This object represents the specific language model to be used by the agent.
# 'model' is set to "gemini-2.0-flash", specifying the Gemini model to use.
# 'openai_client' is set to the 'external_client' we configured earlier, ensuring the model uses the Gemini API.
model = OpenAIChatCompletionsModel(
    model = "gemini-2.0-flash",
    openai_client = external_client
)

# Create an instance of the 'Agent' class.
# 'name' is set to "Assistant", giving the agent a name.
# 'instructions' provides a high-level description of the agent's role and capabilities.
# 'model' is set to the 'model' we created, linking the agent to the Gemini language model.
agent = Agent(
   name="Assistant",
        instructions="A helpful assistant that can answer questions and provide information.",
        model=model,)

# Define a function named 'my_first_agent'.
def my_first_agent():
    # Use the 'Runner.run_sync' method to execute the 'agent' with the input "Hello World!".
    result = Runner.run_sync(
        agent, "Hello World!"
    )
    # Print the 'final_output' attribute of the 'result' object.
    # This contains the final output generated by the agent.
    print(result.final_output)